name: Git and docker test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dhaneshvl/git-docker-test
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: [AWS_EC2_RUNNER]
    steps:
      - name: Pull the image from Docker Hub
        run: docker pull dhaneshvl/git-docker-test:latest
      - name: Run Docker image on AWS EC2
        run: docker run -d -p 8080:8080 dhaneshvl/git-docker-test:latest
